package me.pljr.kitmanager.enums;

public enum Lang {
    NO_CONSOLE,
    KIT_SUCCESS,
    KIT_FAILURE_NO_KIT,
    KIT_FAILURE_COOLDOWN,
    KITS_SUCCESS_TITLE,
    KITS_SUCCESS_FORMAT_AVAILABLE,
    KITS_SUCCESS_FORMAT_UNAVAILABLE,
    AKIT_GIVE_SUCCESS,
    AKIT_GIVE_SUCCESS_NOTIFY,
    AKIT_CREATE_SUCCESS,
    AKIT_REMOVE_SUCCESS
}
