# Big thanks and love for using my plugins! ^^

#|--------------------------------------------------------------------------------------------------------------------|#
# Plugin: KitManager
# Author: https://www.mc-market.org/members/89497/
# Description: Plugin for managing in-game kits.
# Dependencies:
#   -> PLJRApi
#|--------------------------------------------------------------------------------------------------------------------|#

###############\
# MySQL Setup ##############################################################################################\
############### This is the most important part, as the plugin can not work without proper MySQL Database. # \
              ##############################################################################################  \
mysql:
  enabled: false
  host: "127.0.0.1"
  port: "3306"
  database: "db"
  username: "root"
  password: ""
#|--------------------------------------------------------------------------------------------------------------------|#

##############\
# Lang Setup ################################################################\
############## Here, you can customize messages, send by the plugin itself. # \
             ################################################################  \
help:
  - ""
  - "§a§lKitManager Help v${project.version}"
  - ""
  - "§e/kit help §8» §fDisplays this message."
  - "§e/kit <name> §8» §fGives the desired kit."
  - "§e/kit list §8» §fShows all kits, that you can get."
  - ""

admin-help:
  - ""
  - "§a§lKitManager Admin-Help v${project.version}"
  - ""
  - "§e/akit help §8» §fDisplays this message."
  - "§e/akit <name> §8» §fGives desired kit, ignores permission and cooldown."
  - "§e/akit give <player> <name> §8» §fGives desired kit to player, ignoring his permissions and cooldowns."
  - "§e/akit create <name> <cooldown> §8» §fCreates kit from items in you inventory."
  - "§e/akit remove <name> §8» §fRemoves desired kit."
  - ""

lang:
  NO_CONSOLE: "§aKitManager §8» §fThis command is for in-game use only!"
  KIT_SUCCESS: "§aKitManager §8» §fYou have received kit §b{kit}§f."
  KIT_FAILURE_NO_KIT: "§aKitManager §8» §b{kit} §fcould not be found."
  KIT_FAILURE_COOLDOWN: "§aKitManager §8» §fYou must wait %time §fto get this kit!"
  KITS_SUCCESS_TITLE: "§aKitManager §8» §fYour kits:"
  KITS_SUCCESS_FORMAT_AVAILABLE: "§7- §f{name} <hover:show_text:'§eClick to get'><click:run_command:/kit {name}>§e#</click></hover> <hover:show_text:'§cClick to remove'><click:run_command:/akit remove {name}>§c✕</click></hover>"
  KITS_SUCCESS_FORMAT_UNAVAILABLE: "§7- §7{name} <hover:show_text:'§cClick to remove'><click:run_command:/akit remove {name}>§c✕</click></hover>"
  AKIT_GIVE_SUCCESS: "§aKitManager §8» §fYou have successfully given §b{player} §fkit §b{kit}§f."
  AKIT_GIVE_SUCCESS_NOTIFY: "§aKitManager §8» §fYou have received kit §b{kit} §ffrom §b{player}§f."
  AKIT_CREATE_SUCCESS: "§aKitManager §8» §fSuccessfully created kit §b{kit} §fwith cooldown §b{cooldown}§f."
  AKIT_REMOVE_SUCCESS: "§aKitManager §8» §fSuccessfully removed kit §b{kit}§f."
#|--------------------------------------------------------------------------------------------------------------------|#